Personaleinsatzplan/urls.py
from django.contrib import admin
from django.urls import path, include
from PersonaleinsatzplanHaeH.views import StartseiteView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', StartseiteView.as_view(), name='startseite'),
    path('PersonaleinsatzplanHaeH/', include('PersonaleinsatzplanHaeH.urls')),
    path('custom-login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
]

PersonaleinsatzplanHaeH/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    PersonaleinsatzplanCreateView, PersonaleinsatzplanDetailView,
    PersonaleinsatzplanUpdateView, PersonaleinsatzplanDeleteView,
    AuftragCreateView, AuftragListView, AuftragDetailView, AuftragUpdateView, AuftragDeleteView,
    BetreuungsschluesselCreateView,
    BetreuungsschluesselDeleteView,
    MitarbeiterCreateView, MitarbeiterListView, MitarbeiterDetailView, MitarbeiterUpdateView, MitarbeiterDeleteView,
    MitarbeiterBetreuungsschluesselCreateView,
    MitarbeiterBetreuungsschluesselDeleteView, StartseiteView, PersonaleinsatzplaeneFuerNiederlassungView,
    NiederlassungPersonaleinsatzplanuebersicht, GesamtPersonaleinsatzplanUebersicht,
    Personaleinsatzplanuebersicht,
    PersonaleinsatzplanOverviewPDFView, PersonaleinsatzplanDetail2, PersonaleinsatzplanList2View, custom_logout_view)




app_name = 'PersonaleinsatzplanHaeH'
urlpatterns = [

    path('custom-login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', custom_logout_view, name='logout'),
    path('', StartseiteView.as_view(), name='startseite'),
    # Personaleinsatzplan URLs
    path('personaleinsatzplan/create/', PersonaleinsatzplanCreateView.as_view(), name='personaleinsatzplan_create'),
    path("personaleinsatzplan/list/", PersonaleinsatzplanList2View.as_view(), name="personaleinsatzplan_list"),
    path('personaleinsatzplan/list2/', PersonaleinsatzplanList2View.as_view(), name='personaleinsatzplan_list2'),
    path('personaleinsatzplan/<int:pk>/', PersonaleinsatzplanDetailView.as_view(), name='personaleinsatzplan_detail'),
    path('personaleinsatzplan/<int:pk>/detail2/', PersonaleinsatzplanDetail2.as_view(), name='personaleinsatzplan_detail2'),
    path('personaleinsatzplan/<int:pk>/update/', PersonaleinsatzplanUpdateView.as_view(), name='personaleinsatzplan_update'),
    path('personaleinsatzplan/<int:pk>/delete/', PersonaleinsatzplanDeleteView.as_view(), name='personaleinsatzplan_delete'),

    # Auftrag URLs
    path('auftrag/create/', AuftragCreateView.as_view(), name='auftrag_create'),
    path('auftrag/list/', AuftragListView.as_view(), name='auftrag_list'),
    path('auftrag/<int:pk>/', AuftragDetailView.as_view(), name='auftrag_detail'),
    path('auftrag/<int:pk>/update/', AuftragUpdateView.as_view(), name='auftrag_update'),
    path('auftrag/<int:pk>/delete/', AuftragDeleteView.as_view(), name='auftrag_delete'),

    # Betreuungsschluessel URLs
    path('betreuungsschluessel/create/', BetreuungsschluesselCreateView.as_view(), name='betreuungsschluessel_create'),
    path('betreuungsschluessel/<int:pk>/delete/', BetreuungsschluesselDeleteView.as_view(), name='betreuungsschluessel_delete'),

    # Mitarbeiter URLs
    path('mitarbeiter/create/', MitarbeiterCreateView.as_view(), name='mitarbeiter_create'),
    path('mitarbeiter/list/', MitarbeiterListView.as_view(), name='mitarbeiter_list'),
    path('mitarbeiter/<int:pk>/', MitarbeiterDetailView.as_view(), name='mitarbeiter_detail'),
    path('mitarbeiter/<int:pk>/update/', MitarbeiterUpdateView.as_view(), name='mitarbeiter_update'),
    path('mitarbeiter/<int:pk>/delete/', MitarbeiterDeleteView.as_view(), name='mitarbeiter_delete'),


    # MitarbeiterBetreuungsschluessel URLs
    path('mitarbeiter-betreuungsschluessel/create/<int:schluessel_id>/', MitarbeiterBetreuungsschluesselCreateView.as_view(), name='mitarbeiter_betreuungsschluessel_create'),
    path('mitarbeiter-betreuungsschluessel/<int:pk>/delete/', MitarbeiterBetreuungsschluesselDeleteView.as_view(), name='mitarbeiter_betreuungsschluessel_delete'),



    # Personaleinsatzplan Übersicht
    path('personaleinsatzplan/<int:pk>/uebersicht/', Personaleinsatzplanuebersicht.as_view(), name='personaleinsatzplan_uebersicht'),

    path('niederlassung/<int:pk>/personaleinsatzplan_uebersicht/', NiederlassungPersonaleinsatzplanuebersicht.as_view(), name='niederlassung_personaleinsatzplan_uebersicht'),

    path('personaleinsatzplaene/gesamt-uebersicht/', GesamtPersonaleinsatzplanUebersicht.as_view(), name='gesamt_personaleinsatzplan_uebersicht'),

    # Personaleinsatzplanübersicht Ausgabe als PDF Bericht

    path('personaleinsatzplaene/pdf/', PersonaleinsatzplanOverviewPDFView.as_view(), name='alle_personaleinsatzplaene_pdf'),
    path('personaleinsatzplan/<int:pk>/pdf/', PersonaleinsatzplanOverviewPDFView.as_view(), name='personaleinsatzplan_pdf'),
    path('niederlassung/<int:niederlassung_pk>/personaleinsatzplaene/pdf/', PersonaleinsatzplanOverviewPDFView.as_view(), name='niederlassung_personaleinsatzplaene_pdf'),

    path('personaleinsatzplan/<int:pk>/pdf/', PersonaleinsatzplanOverviewPDFView.as_view(), name='personaleinsatzplan_pdf'),
    path('niederlassung/<int:niederlassung_pk>/personaleinsatzplaene/pdf/', PersonaleinsatzplanOverviewPDFView.as_view(), name='niederlassung_personaleinsatzplaene_pdf'),
    # Neue urls für Anwendungsversion

    path('niederlassung/<int:pk>/personaleinsatzplaene/', PersonaleinsatzplaeneFuerNiederlassungView.as_view(), name='personaleinsatzplaene_fuer_niederlassung'),
]

PersonaleinsatzplanHaeH/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Sum

class Niederlassung(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Position(models.Model):
    bezeichnung = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.bezeichnung

class Mitarbeiter(models.Model):
    vorname = models.CharField(max_length=255)
    nachname = models.CharField(max_length=255)
    qualifikation = models.CharField(max_length=255)
    max_woechentliche_arbeitszeit = models.IntegerField()
    personalnummer = models.IntegerField(unique=True, null=False)
    geburtsdatum = models.DateField()
    vertragsbeginn = models.DateField()
    vertragsendeBefristet = models.DateField(blank=True, null=True)
    unbefristet = models.BooleanField(default=False)
    niederlassung = models.ForeignKey(Niederlassung, on_delete=models.PROTECT, null=True, blank=True)

    def __str__(self):
        return f"{self.vorname} {self.nachname}"

    def get_absolute_url(self):
        return reverse('PersonaleinsatzplanHaeH:mitarbeiter_detail', args=[str(self.id)])


class PersonaleinsatzplanStatus(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name

class Personaleinsatzplan(models.Model):
    STATUS_CHOICES = [
        ('entwurf', 'Entwurf'),
        ('in_bearbeitung', 'in Bearbeitung'),
        ('gueltig', 'Gültig'),
        ('archiviert', 'Archiviert'),
        ('storniert', 'Storniert')
    ]

    name = models.CharField(max_length=255)
    gueltigkeit_monat = models.IntegerField(choices=[
        (1, "Januar"), (2, "Februar"), (3, "März"), (4, "April"),
        (5, "Mai"), (6, "Juni"), (7, "Juli"), (8, "August"),
        (9, "September"), (10, "Oktober"), (11, "November"), (12, "Dezember")
    ])
    gueltigkeit_jahr = models.IntegerField()
    kostentraeger = models.CharField(max_length=255)
    ersteller = models.CharField(max_length=255)
    version = models.IntegerField(blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='entwurf')
    niederlassung = models.ForeignKey(
        'Niederlassung', on_delete=models.PROTECT, related_name='personaleinsatzplaene'
    )

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        monat_choices = dict(self._meta.get_field('gueltigkeit_monat').choices)
        monat = monat_choices.get(self.gueltigkeit_monat, "Unbekannt")

        self.name = f"Personaleinsatzplan {self.niederlassung.name} - {monat} {self.gueltigkeit_jahr}"
        super().save(*args, **kwargs)


class Auftrag(models.Model):
    name = models.CharField(max_length=255)
    vergabenummer = models.CharField(max_length=255, unique=True)
    optionsnummer = models.CharField(max_length=255, unique=True)
    massnahmenummer = models.CharField(max_length=255, unique=True)
    startdatum = models.DateField()
    enddatum = models.DateField()
    max_klienten = models.IntegerField(default=0)
    mindest_klienten = models.IntegerField(default=0)
    aktuell_klienten = models.IntegerField(default=0)
    personaleinsatzplan = models.ForeignKey(Personaleinsatzplan, on_delete=models.CASCADE, related_name='auftraege')

    def __str__(self):
        return self.name


class Betreuungsschluessel(models.Model):
    name = models.CharField(max_length=255)
    position = models.ForeignKey(Position, on_delete=models.PROTECT)
    klienten_pro_betreuer = models.IntegerField()
    auftrag = models.ForeignKey(Auftrag, on_delete=models.CASCADE, related_name='betreuungsschluessel', blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def abgedeckte_VZA(self):
        total_stunden = MitarbeiterBetreuungsschluessel.objects.filter(
            schluessel=self
        ).aggregate(total=Sum('anteil_stunden_pro_woche'))['total']

        vza_wert = VollzeitaequivalentStunden.objects.first().wert if VollzeitaequivalentStunden.objects.exists() else 1
        abgedeckte_vza = (total_stunden / vza_wert) if total_stunden else 0
        return round(abgedeckte_vza, 1)

    @property
    def benoetigte_VZA_max(self):
        if self.auftrag:
            return self.auftrag.max_klienten / self.klienten_pro_betreuer
        return 0

    @property
    def benoetigte_VZA_mindest(self):
        if self.auftrag:
            return self.auftrag.mindest_klienten / self.klienten_pro_betreuer
        return 0

    @property
    def benoetigte_VZA_aktuell(self):
        if self.auftrag:
            return self.auftrag.aktuell_klienten / self.klienten_pro_betreuer
        return 0

    @property
    def differenz_VZA_max(self):
        return round(self.benoetigte_VZA_max - self.abgedeckte_VZA, 1)

    @property
    def differenz_VZA_mindest(self):
        return round(self.benoetigte_VZA_mindest - self.abgedeckte_VZA, 1)

    @property
    def differenz_VZA_aktuell(self):
        return round(self.benoetigte_VZA_aktuell - self.abgedeckte_VZA, 1)


class MitarbeiterBetreuungsschluessel(models.Model):
    position = models.ForeignKey(Position, on_delete=models.PROTECT)
    anteil_stunden_pro_woche = models.FloatField()
    kommentar = models.TextField(blank=True, null=True)
    mitarbeiter = models.ForeignKey(Mitarbeiter, on_delete=models.PROTECT, related_name='betreuungsschluessel_zuweisungen')
    schluessel = models.ForeignKey(Betreuungsschluessel, on_delete=models.PROTECT, related_name='mitarbeiter_zuweisungen')
    auftrag = models.ForeignKey(Auftrag, on_delete=models.PROTECT, related_name='mitarbeiter_betreuungsschluessel')
    freie_stunden = models.FloatField(default=0)
    total_hours = models.FloatField(default=0)

    def __str__(self):
        return f"{self.mitarbeiter} - {self.schluessel}"

    @staticmethod
    def calculate_hours_and_free_time(mitarbeiter, personaleinsatzplan):

        if not mitarbeiter or not personaleinsatzplan:
            return {"total_hours": 0, "free_hours": 0}

        # Summe der Stunden pro Woche berechnen
        queryset = MitarbeiterBetreuungsschluessel.objects.filter(
            mitarbeiter=mitarbeiter,
            schluessel__auftrag__personaleinsatzplan__gueltigkeit_monat=personaleinsatzplan.gueltigkeit_monat,
            schluessel__auftrag__personaleinsatzplan__gueltigkeit_jahr=personaleinsatzplan.gueltigkeit_jahr,
            schluessel__auftrag__personaleinsatzplan__status=personaleinsatzplan.status,
        )

        aggregation_result = queryset.aggregate(total_stunden=Sum('anteil_stunden_pro_woche'))

        total_hours = aggregation_result['total_stunden'] or 0

        max_arbeitszeit = mitarbeiter.max_woechentliche_arbeitszeit

        free_hours = max_arbeitszeit - total_hours

        return {"total_hours": total_hours, "free_hours": free_hours}


class VollzeitaequivalentStunden(models.Model):
    wert = models.IntegerField()

    def __str__(self):
        return str(self.wert)

templates/mitarbeiter_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Personaleinsatzpläne</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body class="mitarbeiter-detail-page">

<div class="navbar">
    <a href="{% url 'PersonaleinsatzplanHaeH:logout' %}" class="logout-link">Abmelden</a>
</div>

<h1 class="mitarbeiter-header">{{ mitarbeiter.vorname }} {{ mitarbeiter.nachname }}</h1>
<div class="actions">
    <a href="{% url 'PersonaleinsatzplanHaeH:mitarbeiter_update' mitarbeiter.pk %}" class="action-link">Bearbeiten</a>
    <a href="{% url 'PersonaleinsatzplanHaeH:mitarbeiter_delete' mitarbeiter.pk %}" class="action-link">Löschen</a>
</div>

<section>
    <table class="detail-table">
        <thead>
            <tr>
                <th>Geburtsdatum</th>
                <th>Qualifikation</th>
                <th>Personalnummer</th>
                <th>Vertragsbeginn</th>
                <th>Vertragsende</th>
                <th>Unbefristet</th>
                <th>Niederlassung</th>
                <th>Maximale wöchentliche Arbeitszeit</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ mitarbeiter.geburtsdatum|date:"d.m.Y" }}</td>
                <td>{{ mitarbeiter.qualifikation }}</td>
                <td>{{ mitarbeiter.personalnummer }}</td>
                <td>{{ mitarbeiter.vertragsbeginn|date:"d.m.Y" }}</td>
                <td>
                    {% if mitarbeiter.vertragsendeBefristet %}
                    {{ mitarbeiter.vertragsendeBefristet|date:"d.m.Y" }}
                    {% else %}
                        -
                    {% endif %}
                </td>
                <td>{{ mitarbeiter.unbefristet|yesno:"Ja,Nein" }}</td>
                <td>{{ mitarbeiter.niederlassung }}</td>
                <td>{{ mitarbeiter.max_woechentliche_arbeitszeit }} Stunden</td>
            </tr>
        </tbody>
    </table>
</section>

<section>
    <table class="auftrag-table">
        <thead>
            <tr>
                <th>Auftrag</th>
                <th>Anteil Stunden pro Woche</th>
            </tr>
        </thead>
        <tbody>
            {% for auftrag_info in auftraege_info %}
            <tr>
                <td>
                    <a href="{% url 'PersonaleinsatzplanHaeH:auftrag_detail' auftrag_info.auftrag.pk %}?next={{ request.path }}" class="auftrag-link">
                        {{ auftrag_info.auftrag.name }}
                    </a>
                </td>
                <td>{{ auftrag_info.anteil_stunden_pro_woche }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</section>

<div class="link-container">
    <a href="{{ zurueck_link }}" class="action-link">Zurück</a>
</div>

</body>
</html>

templates/personaleinsatzplan_uebersicht.html
<!DOCTYPE html>
<html lang="de">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
    <title>Personaleinsatzplanübersicht</title>
</head>
<body class="personaleinsatzplan-seite">

<div class="navbar">
    <a href="{% url 'PersonaleinsatzplanHaeH:logout' %}" class="logout-link">Abmelden</a>
</div>

<h2>{{ personaleinsatzplan.name }}</h2>

<div class="actions">
    <a href="{% url 'PersonaleinsatzplanHaeH:personaleinsatzplan_update' personaleinsatzplan.pk %}?next={{ request.path }}" class="action-link2">
        Bearbeiten
    </a>
    <a href="{% url 'PersonaleinsatzplanHaeH:personaleinsatzplan_delete' personaleinsatzplan.pk %}?next={{ request.path }}" class="action-link2">
        Löschen
    </a>
</div>

<section>
    <table>
        <tbody>
            <tr>
                <td><strong>Gültigkeit</strong></td>
                <td>{{ personaleinsatzplan.get_gueltigkeit_monat_display }} {{ personaleinsatzplan.gueltigkeit_jahr }}</td>
                <td><strong>Kostenträger</strong></td>
                <td>{{ personaleinsatzplan.kostentraeger }}</td>
            </tr>
            <tr>
                <td><strong>Ersteller</strong></td>
                <td>{{ personaleinsatzplan.ersteller }}</td>
                <td><strong>Status</strong></td>
                <td>{{ personaleinsatzplan.get_status_display }}</td>
            </tr>
        </tbody>
    </table>
</section>

{% if auftrag_details %}
    {% for auftrag_detail in auftrag_details %}
    <section>
            <a href="{% url 'PersonaleinsatzplanHaeH:auftrag_detail' auftrag_detail.auftrag.id %}?next={{ request.path }}" class="auftrag-detail-link">
                {{ auftrag_detail.auftrag.name }}
            </a>

        <table>
            <tr>
                <td><strong>Startdatum</strong></td>
                <td>{{ auftrag_detail.auftrag.startdatum|date:"d.m.Y" }}</td>
                <td><strong>Enddatum</strong></td>
                <td>{{ auftrag_detail.auftrag.enddatum|date:"d.m.Y" }}</td>
                <td><strong>Aktuelle Teilnehmer:innen</strong></td>
                <td>{{ auftrag_detail.auftrag.aktuell_klienten}}</td>
            </tr>
            <tr>
                <td><strong>Vergabenummer</strong></td>
                <td>{{ auftrag_detail.auftrag.vergabenummer }}</td>
                <td><strong>Optionsnummer</strong></td>
                <td>{{ auftrag_detail.auftrag.optionsnummer }}</td>
                <td><strong>Maßnahmenummer</strong></td>
                <td>{{ auftrag_detail.auftrag.massnahmenummer }}</td>
            </tr>
        </table>

        {% for betreuungsschluessel in auftrag_detail.betreuungsschluessel %}
        <section>
            <h4>Betreuungsschlüssel: {{ betreuungsschluessel.name }}</h4>
            <table>
                <thead>
                    <tr>
                        <th>Teilnehmer:innen pro Betreuer:in</th>
                        <th>{{ betreuungsschluessel.klienten_pro_betreuer }}</th>
                        <th>Derzeit abgedeckte Vollzeitstellen</th>
                        <th>{{ betreuungsschluessel.abgedeckte_VZA }}</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Gesamtbedarf an Vollzeitstellen</td>
                        <td>{{ betreuungsschluessel.benoetigte_VZA_max }}</td>
                        <td>Mindestbedarf an Vollzeitstellen</td>
                        <td>{{ betreuungsschluessel.benoetigte_VZA_mindest }}</td>
                        <td>Benötigte Vollzeitstellen für aktuelle Teilnehmer:innen</td>
                        <td>{{ betreuungsschluessel.benoetigte_VZA_aktuell }}</td>
                    </tr>
                    <tr>
                        <td>Differenz zum Gesamtbedarf</td>
                        <td class="{% if betreuungsschluessel.differenz_VZA_max > betreuungsschluessel.benoetigte_VZA_max %}highlight-error{% endif %}">
                            {{ betreuungsschluessel.differenz_VZA_max }}
                        </td>
                        <td>Differenz zum Mindestbedar</td>
                        <td class="{% if betreuungsschluessel.differenz_VZA_mindest <= betreuungsschluessel.benoetigte_VZA_mindest %}highlight-error{% endif %}">
                            {{ betreuungsschluessel.differenz_VZA_mindest }}
                        </td>
                        <td>Differenz für aktuelle Teilnehmer:innen</td>
                        <td class="{% if betreuungsschluessel.differenz_VZA_aktuell <= betreuungsschluessel.benoetigte_VZA_aktuell %}highlight-error{% endif %}">
                            {{ betreuungsschluessel.differenz_VZA_aktuell }}
                        </td>
                    </tr>
                </tbody>
            </table>

            <h4>Mitarbeiter:innen des Auftrags:</h4>
            <table>
                <thead>
                    <tr>
                        <th>Nachname, Vorname</th>
                        <th>Geburtsdatum</th>
                        <th>Qualifikation</th>
                        <th>Max. wöchentliche Arbeitszeit</th>
                        <th>Anteil Stunden im Projekt</th>
                        <th>Bereits zugewiesene Stunden</th>
                        <th>Verbleibende Stunden</th>
                        <th>Kommentar</th>
                        <th>Aktionen</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mitarbeiter in betreuungsschluessel.mitarbeiter %}
                    <tr>
                        <td>
                            <a href="{% url 'PersonaleinsatzplanHaeH:mitarbeiter_detail' mitarbeiter.id %}?next={{ request.path }}" class="card-link2">
                                {{ mitarbeiter.nachname }}, {{ mitarbeiter.vorname }}
                            </a>
                        </td>
                        <td>{{ mitarbeiter.geburtsdatum }}</td>
                        <td>{{ mitarbeiter.qualifikation }}</td>
                        <td>{{ mitarbeiter.max_woechentliche_arbeitszeit }}</td>
                        <td>{{ mitarbeiter.anteil_stunden_pro_woche }}</td>
                        <td>{{ mitarbeiter.zugewiesene_stunden }}</td>
                        <td class="{% if mitarbeiter.freie_stunden == 0 or mitarbeiter.freie_stunden is None %}highlight-error{% endif %}">
                            {{ mitarbeiter.freie_stunden }}
                        </td>
                        <td>{{ mitarbeiter.kommentar }}</td>
                        <td>
                            <a href="{% url 'PersonaleinsatzplanHaeH:mitarbeiter_betreuungsschluessel_delete' mitarbeiter.mitarbeiter_betreuungsschluessel_id %}" class="action-link">
                                Entfernen
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="9">Keine Mitarbeiter:innen zugewiesen.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            
            <a href="{% url 'PersonaleinsatzplanHaeH:mitarbeiter_betreuungsschluessel_create' betreuungsschluessel.id %}?next={{ request.path }}" class="auftrag-detail-link2">
                Mitarbeiter zuweisen
            </a>
        </section>
        {% empty %}
        <p>Klicke auf den Namen des Auftrags und erstelle einen neuen Betreuungsschlüssel.</p>
        {% endfor %}
    </section>
    {% endfor %}
{% else %}
    <p>Klicke auf "Neuer Auftrag", um einen Auftrag zu erstellen.</p>
{% endif %}

<div class="link-container">
    <a href="{% url 'PersonaleinsatzplanHaeH:auftrag_create' %}?personaleinsatzplan_id={{ personaleinsatzplan.pk }}&next={{ request.path }}" class="action-link">
        Neuer Auftrag
    </a>
    <a href="{% url 'PersonaleinsatzplanHaeH:personaleinsatzplan_pdf' personaleinsatzplan.pk %}" class="action-link">
        Personaleinsatzplan drucken
    </a>
    <a href="{{ zurueck_link }}" class="action-link">Zurück</a>
</div>

</body>
</html>

templates/startseite.html
<!DOCTYPE html>
<html lang="de">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">
</head>
<body>

<div class="navbar">
    <a href="{% url 'PersonaleinsatzplanHaeH:logout' %}" class="logout-link">Abmelden</a>
</div>

<h1>Willkommen zur F1 Personaleinsatzplanung</h1>

<h3>Wähle deine Niederlassung</h3>

<div class="card-container">
    {% for niederlassung in niederlassungen %}
    <a href="{% url 'PersonaleinsatzplanHaeH:personaleinsatzplaene_fuer_niederlassung' niederlassung.pk %}?next={% url 'PersonaleinsatzplanHaeH:startseite' %}" class="card-link-wrapper">
        <div class="card">
            <h4>{{ niederlassung.name }}</h4>
            <span class="card-link">Personaleinsatzpläne ansehen</span>
        </div>
    </a>
    {% endfor %}
</div>

<div class="link-container">
    <a href="{% url 'PersonaleinsatzplanHaeH:personaleinsatzplan_list2' %}?next={{ request.path }}" class="action-link">
        Liste aller Personaleinsatzpläne
    </a>
    <a href="{% url 'PersonaleinsatzplanHaeH:auftrag_list' %}?next={{ request.path }}" class="action-link">
        Liste aller Aufträge
    </a>
    <a href="{% url 'PersonaleinsatzplanHaeH:mitarbeiter_list' %}?next={{ request.path }}" class="action-link">
        Liste aller Mitarbeiter
    </a>
    <a href="{% url 'PersonaleinsatzplanHaeH:alle_personaleinsatzplaene_pdf' %}" class="action-link">
        Alle Personaleinsatzpläne als PDF herunterladen
    </a>
</div>

</body>
</html>